#!/usr/local/bin/node
require.paths.unshift(__dirname + '/../lib');

var database = require('database');

if (process.argv[2] == 'clear') {
  database.Tweet.remove({}, function(error){
    if (error){
      console.log("There was an error clearing the database:")
      console.log(error)
    } else {
      console.log("Database cleared")
    }
    process.exit()
  })
  
} else if (process.argv[2] == 'clear_mocks') {
  database.destroy_mocks(function(error){
    if (error){
      console.log("There was an error clearing the mocks:")
      console.log(error)
    } else {
      console.log("Mocks cleared")
    }
    process.exit()
  })
}